name: tests

on:
  push

jobs:

  tests:

    strategy:

      fail-fast: false

      matrix:

        os:
          - ubuntu-latest
          - windows-latest

        php_version:
          - 8.3
          - 8.4

    runs-on: ${{ matrix.os }}

    name: Testing with PHP ${{ matrix.php_version }} running on ${{ matrix.os }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          extensions: curl
          tools: composer:v2

      - name: Install dependencies
        run: composer install

      - name: Running tests
        run: ./vendor/bin/phpunit --coverage-clover coverage.xml --log-junit junit.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
